aws_region          = "ap-south-1"
instance_type       = "t3.micro"
ami_id              = "ami-034a8236c75419857"
instance_name       = "terraform-ec2"
bucket_name         = "terraform-demo-bucket-sulaiman-2026"
lambda_function_name = "terraform-demo-lambda"
role_name           = "terraform-demo-role"
key_name            = "terraform-key"
