name: Terraform CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-cd:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Vault CLI
      - name: Install Vault
        run: |
          wget https://releases.hashicorp.com/vault/1.15.5/vault_1.15.5_linux_amd64.zip
          unzip vault_1.15.5_linux_amd64.zip
          sudo mv vault /usr/local/bin/

      # Fetch AWS Credentials from Vault
      - name: Fetch AWS Credentials from Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

        run: |
          vault status

          vault kv get secret/aws

          ACCESS_KEY=$(vault kv get -field=access_key secret/aws)

          SECRET_KEY=$(vault kv get -field=secret_key secret/aws)

          echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY" >> $GITHUB_ENV

          echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY" >> $GITHUB_ENV

          echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV

          echo "Credentials Loaded Successfully"

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply --auto-approve
